// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var dragObj, findObj, getPixelPosOfObject, getPixelPosOfObjectWithinGroup, hoverFun, isDrag, isSelected, mouseDownFun, mouseMoveFun, mouseUpFun, path, rect, rect2,
      _this = this;
    this.isMouseDown = false;
    this.isMouseDragged = false;
    this.currentlySelected = null;
    getPixelPosOfObject = function(object, axis) {
      if (axis === 'x') {
        return object.get('left') - (object.get('width') / 2);
      } else if (axis === 'y') {
        return object.get('top') - (object.get('height') / 2);
      } else {
        return console.log('No axis defined');
      }
    };
    getPixelPosOfObjectWithinGroup = function(object, parentGroup, axis) {
      if (axis === 'x') {
        return object.get('left') + ((parentGroup.get('width') / 2) - (object.get('width') / 2));
      } else if (axis === 'y') {
        return object.get('top') + ((parentGroup.get('height') / 2) - (object.get('height') / 2));
      } else {
        return console.log('No axis defined');
      }
    };
    mouseDownFun = function(e) {
      console.log(e.e.layerX);
      console.log(e);
      _this.isMouseDown = true;
      _this.selectedObj = findObj(e.e.layerX, e.e.layerY);
      if (_this.currentlySelected) {
        return _this.currentlySelected.obj.set('active', true);
      }
    };
    mouseUpFun = function(e) {
      _this.isMouseDown = false;
      if (_this.currentlySelected !== null) {
        _this.currentlySelected.obj.set('active', false);
        _this.canvas.renderAll();
        return _this.currentlySelected = null;
      }
    };
    mouseMoveFun = function(e) {
      var currentX, currentY;
      if (_this.isMouseDown && _this.currentlySelected) {
        currentX = _this.currentlySelected.obj.get('left');
        currentY = _this.currentlySelected.obj.get('top');
        console.log(e.e.layerX);
        console.log(_this.currentlySelected.masterGroupY);
        _this.currentlySelected.obj.set('left', (e.e.layerX - _this.currentlySelected.masterGroupX) - ((_this.currentlySelected.masterGroup.get('width') / 2) - (_this.currentlySelected.objWidth / 2)) - _this.currentlySelected.selectedAreaX);
        _this.currentlySelected.obj.set('top', (e.e.layerY - _this.currentlySelected.masterGroupY) - ((_this.currentlySelected.masterGroup.get('height') / 2) - (_this.currentlySelected.objHeight / 2)) - _this.currentlySelected.selectedAreaY);
        _this.canvas.renderAll();
        return console.log(_this.currentlySelected);
      }
    };
    hoverFun = function(e) {
      console.log('object Over');
      return console.log(e);
    };
    isDrag = function(e) {};
    findObj = function(mouseX, mouseY) {
      var XPositionInGroup, YPositionInGroup, index, masterGroupX, masterGroupY, obj, objHeight, objPosX, objPosY, objWidth, _ref, _results;
      masterGroupX = getPixelPosOfObject(_this.masterGroup, 'x');
      console.log("masterGroupX: " + masterGroupX);
      masterGroupY = getPixelPosOfObject(_this.masterGroup, 'y');
      console.log("masterGroupY: " + masterGroupY);
      _ref = _this.masterGroup.objects;
      _results = [];
      for (index in _ref) {
        obj = _ref[index];
        objWidth = obj.get('width');
        objHeight = obj.get('height');
        XPositionInGroup = getPixelPosOfObjectWithinGroup(obj, _this.masterGroup, 'x');
        YPositionInGroup = getPixelPosOfObjectWithinGroup(obj, _this.masterGroup, 'y');
        objPosX = XPositionInGroup + masterGroupX;
        objPosY = YPositionInGroup + masterGroupY;
        if (isSelected(mouseX, mouseY, objPosX, objPosY, objWidth, objHeight)) {
          _results.push(_this.currentlySelected = {
            obj: obj,
            masterGroup: _this.masterGroup,
            objWidth: objWidth,
            objHeight: objHeight,
            mouseX: mouseX,
            mouseY: mouseY,
            selectedAreaX: mouseX - objPosX,
            selectedAreaY: mouseY - objPosY,
            masterGroupX: masterGroupX,
            masterGroupY: masterGroupY
          });
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };
    isSelected = function(mouseX, mouseY, objPosX, objPosY, objWidth, objHeight) {
      if (mouseX >= objPosX && mouseX <= objPosX + objWidth) {
        if (mouseY >= objPosY && mouseY <= objPosY + objHeight) {
          console.log('found');
          return true;
        } else {
          return false;
        }
      } else {
        return false;
      }
    };
    dragObj = function(obj, top, left) {};
    this.canvas = new fabric.Canvas('canvas');
    this.canvas.selection = false;
    path = "M110.689 661.75q34.0957 0 54.4473 -19.6992q21.8965 -19.7002 21.8965 -55.7695v-220.844l141.281 121l0.34375 -0.40625q20.2031 15.5625 45.7188 15.5625q31.0508 0 53.0254 -21.9746t21.9746 -53.0254q0 -21.0391 -10.7559 -38.6787 q-10.7559 -17.6387 -28.6504 -27.3213l-91.0312 -78.6875l135.438 -166.781q13.5 -16.624 13.5 -43.625q-0.00195312 -31.0518 -21.9746 -53.0254q-21.9746 -21.9746 -53.0254 -21.9746q-35.0371 0 -57.5625 26.9688l-130.469 159.812l-17.8125 -15.375v-93.0625 q0 -30.8301 -20.5332 -51.9619t-54.7168 -21.1318q-32.5996 0 -53.1895 20.2246q-20.5938 20.2256 -20.5938 50.9316v510.5q0 32.3896 20.375 55.3672q20.375 22.9766 52.3145 22.9766z";
    rect = new fabric.Rect();
    rect2 = new fabric.Rect();
    this.masterGroup = new fabric.Group();
    this.masterGroup.set('width', 400);
    this.masterGroup.set('height', 400);
    this.masterGroup.set('top', 400);
    this.masterGroup.set('left', 400);
    this.masterGroup.set('selectable', false);
    this.masterGroup.set('strokeWidth', 1);
    this.masterGroup.set('stroke', 'black');
    rect.set('fill', 'red');
    rect.set('width', 100);
    rect.set('height', 100);
    rect.set('left', 0);
    rect.set('top', 0);
    rect2.set('fill', 'black');
    rect2.set('width', 50);
    rect2.set('height', 50);
    rect2.set('left', 25);
    rect2.set('top', 25);
    this.canvas.add(rect2);
    this.masterGroup.add(rect);
    this.canvas.add(this.masterGroup);
    this.canvas.observe('mouse:down', mouseDownFun);
    this.canvas.observe('mouse:up', mouseUpFun);
    this.canvas.observe('mouse:move', mouseMoveFun);
    this.canvas.observe('object:over', hoverFun);
    this.canvas.renderAll();
    return console.log(this.canvas);
  });

}).call(this);
